### ISSUE TITLE
Absent notty dependency

### ISSUE THREAD

**Issue by aluuu** [hannesm/telnet#1]
Hello,

I'm trying to build example unikernel, but I can't find `notty.mirage` package in the OPAM. I assume that it was pinned to some package in your local filesystem path.

Could you please provide this package or point me where I can find it?

**Comment by aluuu** [comment]
Some additional information about my setup.

I'm building exmaple against [my fork](https://github.com/aluuu/telnet)

Steps to reproduce:

```
cd examples
mirage configure --unix && mirage build
```

Output:

```
# Detecting depexts using flags: x86_64 osx homebrew
# No extra OS packages requirements found.

=-=- Synchronising pinned packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[telnet] /Users/admin/workspace/github.com/telnet/ synchronized
[NOTE] Package functoria is already installed (current version is 1.1.1).
[NOTE] Package lwt is already installed (current version is 2.5.2).
[NOTE] Package mirage-clock-unix is already installed (current version is 1.0.0).
[NOTE] Package mirage-console is already installed (current version is 2.1.3).
[NOTE] Package mirage-logs is already installed (current version is 0.2).
[NOTE] Package mirage-net-macosx is already installed (current version is 1.1.0).
[NOTE] Package mirage-types is already installed (current version is 2.8.0).
[NOTE] Package mirage-types-lwt is already installed (current version is 2.8.0).
[NOTE] Package mirage-unix is already installed (current version is 2.6.0).
[NOTE] Package notty is already installed (current version is 0.1.1).
[NOTE] Package tcpip is already installed (current version is 2.8.0).
[NOTE] Package telnet is already installed (current version is 1.0.0).
[ERROR] command terminated with exit code 2
stderr: ocamlfind: Package `notty.mirage' not found
```

**Comment by hannesm** [comment]
the notty.mirage package is actually over there https://github.com/pqwy/notty/tree/mirage

**Comment by aluuu** [comment]
Oh, I didn't noticed, thank you.

**Comment by hannesm** [comment]
please keep in mind that this telnet server is by no means finished (and IIRC esp. the keys example is not a good one, there are ones which work better (you can either come up with some yourself or port those from notty over...))

**Comment by aluuu** [comment]
Sure, I've found this package in the pioneer projects list and I'm just playing around trying to implement something useful. Anyway, thanks for warning.

**Comment by hannesm** [comment]
by digging around on my hard drive, I found another example (now in https://github.com/hannesm/telnet/tree/master/example/outlines) and put the needed notty pin in the README.... HTH, please ask if something is stupid or unclear
